In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
dataset = "https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/Social_Network_Ads.csv"

In [ ]:
df = pd.read_csv(dataset)
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.shape, df.info, df.nunique()


((400, 5),
 <bound method DataFrame.info of       User ID  Gender  Age  EstimatedSalary  Purchased
 0    15624510    Male   19            19000          0
 1    15810944    Male   35            20000          0
 2    15668575  Female   26            43000          0
 3    15603246  Female   27            57000          0
 4    15804002    Male   19            76000          0
 ..        ...     ...  ...              ...        ...
 395  15691863  Female   46            41000          1
 396  15706071    Male   51            23000          1
 397  15654296  Female   50            20000          1
 398  15755018    Male   36            33000          0
 399  15594041  Female   49            36000          1
 
 [400 rows x 5 columns]>,
 User ID            400
 Gender               2
 Age                 43
 EstimatedSalary    117
 Purchased            2
 dtype: int64)

In [ ]:
df.Purchased.value_counts()
# df.Gender  = pd.to_numeric(df.Gender=="Male")
df.iloc[:8]

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    True   19            19000          0
1  15810944    True   35            20000          0
2  15668575   False   26            43000          0
3  15603246   False   27            57000          0
4  15804002    True   19            76000          0
5  15728773    True   27            58000          0
6  15598044   False   27            84000          0
7  15694829   False   32           150000          1

In [ ]:
x = df.iloc[:,2:4].values
y = df.iloc[:,4:].values
x[:3],y[:3]

(array([[True, 19, 19000],
        [True, 35, 20000],
        [False, 26, 43000]], dtype=object),
 array([[0],
        [0],
        [0]]))

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [ ]:
print("X :\n",x.shape, x_train.shape, x_test.shape ,"\nY :\n",y.shape, y_train.shape, y_test.shape)

X :
 (400, 3) (300, 3) (100, 3) 
Y :
 (400, 1) (300, 1) (100, 1)


In [ ]:
scaler = MinMaxScaler()

In [ ]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [ ]:
x_train[:3],x_test[:3]

(array([[0.        , 0.61904762, 0.17777778],
        [1.        , 0.33333333, 0.77777778],
        [0.        , 0.47619048, 0.25925926]]),
 array([[1.        , 0.28571429, 0.53333333],
        [0.        , 0.47619048, 0.25925926],
        [1.        , 0.4047619 , 0.44444444]]))

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
acc = accuracy_score(y_test, y_pred)
acc

0.89

In [ ]:
# without age and scaling : 68%
# with scaling and without age : 89 %
# with scaling and with age : 89 %

In [ ]:
a = scaler.transform([[25,50450]]) # Remove 1st arg if gender isn't used[gender,age,salary]
pred = model.predict(a)
a, pred

(array([[1.        , 0.16666667, 0.26259259]]), array([0]))